---
server.name: kibana
server.host: "0.0.0.0"

# Elasticsearch Connection
elasticsearch.hosts: [ "http://${ELASTICSEARCH_HOST_PORT}" ]


## X-Pack security credentials
elasticsearch.username: ${ELASTIC_USERNAME}
elasticsearch.password: ${ELASTIC_PASSWORD}



#opendistro_security.basicauth.login.brandimage:https://media-exp1.licdn.com/dms/image/C4E0BAQHAgz4mWhjy3A/company-logo_200_200/0/1612870306875?e=2147483647&v=beta&t=ZMfbvIp8e55LzNSi_Lat8vySIziFnUPw0R9RamxsfNA